[package]
name = "rusty_fractal_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
glow = "0.11.2"
egui_glow = "0.19.0"
dirs = "4.0.0"
glam = "0.21.3"
